[package]
name = "tparser"
description.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.86"
serde = {version = "1.0.204", features = ["derive"] }
toml = "0.8.14"
